name: Deploy webby site

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  web:
    name: Deploy webby site
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:latest
      env: { LANG: "C.UTF-8" }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: rollerozxa/tensy
          path: .tensy
          ref: 4bccde2c2ea02f7d699f0622365564abfba6ad16

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev ninja-build xxd zip

      - name: Build Tensy
        run: |
          ./.tensy/packaging/build.sh web
          mkdir -p play
          mv .tensy/packaging/bin/web/* play/

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
